### ISSUE TITLE
using node v20.9.0 result in error

### ISSUE THREAD

**Issue by DaDecky** [zen-browser/docs#65]
**Bug Description**
Using Node v20.9.0 result in error when running `npx quartz build --serve`

**To Reproduce**

1. Clone the repository
2. Change node version to v20.9.0
3. Execute `npm i`
4. Execute `npx quartz build --serve`

**Expected behavior**
Quartz server is running on port 8080

**Fix**
When i change node to v22.10.0, bug is solved

**Screenshots**
![image](https://github.com/user-attachments/assets/46622376-d2bf-40e8-9fdb-ffaa4deefba6)

**Desktop**

- Quartz Version: v4.3.0
- `node` Version: v20.9.0
- `npm` version: v10.9.0
- OS: Windows 11
- Browser : Ms. Edge

**Comment by IAmJafeth** [comment]
Hi @DaDecky!

Thanks for bringing this to our attention! Just a quick note: the Zen Browser documentation uses Quartz 4 as its static site generator, so it would be great to address this issue over in the Quartz 4 repository. You can check out the current issues or submit a new one here: [Quartz Issues](https://github.com/jackyzha0/quartz/issues).

I’ll go ahead and close this issue for now since it’s resolved with Node v22.10.0 as you mentioned. If you have any other questions or need further assistance, feel free to reach out!

Thanks again!
